directory: /mnt/sda/m
library: ~/Beets/musiclibrary.db
import:
    copy: no  # Copy the file to our directory when importing?
    write: no # Automatically write the file on library import / update?
    move: no # move files to library
    resume: ask # Resume interrupted imports?
    autotag: no # 
    incremental: yes # Skip directories we already imported?
    log: /home/dietpi/beets.log   # Where should we write what we do?

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

pluginpath:
    #- ~/.local/lib/python3.8/site-packages/beetsplug
    - /home/dietpi/newbeetplugins/lastupdate/beetsplug
    - /home/dietpi/.local/lib/python3.7/site-packages/beetsplug

plugins: smartplaylist acousticbrainz missing random info bucket the lastimport lastupdate xtractor describe bpmanalyser goingrunning

include:
    - goingrunning.yaml

smartplaylist:
    relative_to: /mnt/sda/m/
    playlist_dir: /mnt/omv/music/playlists
    playlists:
        - name: Never_Listened.m3u
          query: 'play_count: '
        - name: Top_Rated.m3u
          query: 'rating:1'
        - name: Popular_Chill.m3u
          query: ['"genre::(Ambient|Chillout)" play_count:5..']
        - name: UnPlayed_Chill.m3u
          query: ['"genre::(Ambient|Chillout)" play_count: ']
        - name: Popular_DrumBass.m3u
          query: ['genre:"Drum & Bass" play_count:5..']
        - name: UnPlayed_DrumBass.m3u
          query: ['genre:"Drum & Bass" play_count: ']
        - name: Popular_ProgHouseTrance.m3u
          query: ['"genre::(Progressive House|Trance)" play_count:12..']
        - name: UnPlayed_ProgHouseTrance.m3u
          query: ['"genre::(Progressive House|Trance)" play_count:..0']
        # between 0.001 to 1
        - name: UnPlayedAAgressive.m3u
          query: ['mood_aggressive:0.90.. play_count:..0 ^genre:Christmas']
        # between 0.001 to 1
        - name: UnPlayedHappy.m3u
          query: ['mood_happy:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedReallyHappy.m3u
          query: ['mood_happy:0.99.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedSad.m3u
          query: ['mood_sad:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedParty.m3u
          query: ['mood_party:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedReallyParty.m3u
          query: ['mood_party:0.99.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedRelaxed.m3u
          query: ['mood_relaxed:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedDanceable.m3u
          query: ['danceable:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedHarmonicA.m3u
          query: ['"chords_key::(A|D|E|F#)" play_count:..0 ^genre:Christmas']
        - name: UnPlayedHarmonicF.m3u
          query: ['"chords_key::(F|C|Bb|D)" play_count:..0 ^genre:Christmas']
        - name: TopRatedNotPlayedRecently.m3u
          query: ['rating:0.8.. last_played:..-6m ^genre:Christmas']
        - name: UnPlayedAcousticLady.m3u
          query: ['gender:"female" mood_acoustic:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedAcousticGuy.m3u
          query: ['gender:"male" ^gender:"fe" mood_acoustic:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedElectronicLady.m3u
          query: ['gender:"female" mood_electronic:0.95.. play_count:..0 ^genre:Christmas']
        - name: UnPlayedElectronicGuy.m3u
          query: ['gender:"male" ^gender:"fe" mood_electronic:0.95.. play_count:..0 ^genre:Christmas']

acousticbrainz:
    auto: yes

lastfm:
    user: prupertplum

lastimport:
    lastfm.user: prupertplum

bucket:
    bucket_year: ['1980s', '1990s', '2000s', '2010s']
    extrapolate: true
    bucket_alpha: ['A - D', 'E - L', 'M - R', 'S - Z']

lastupdate:
    user: prupertplum 
    apikey: c3e3a25d7295d0e9b712c5ad9f5fa319
    recent_trackcount: 100
    loved_trackcount: 50

bpmanalyser:
  auto: no
  dry-run: no
  write: no
  threads: 4
  force: no
  quiet: no

xtractor:
    auto: no
    dry-run: no
    write: no
    threads: 2
    force: no
    quiet: no
    items_per_run: 0
    keep_output: yes
    keep_profiles: no
    output_path: /mnt/sda/x/_xtraction_data
    low_level_extractor: /home/dietpi/essentia/build/src/examples/essentia_streaming_extractor_music
    high_level_extractor: /home/dietpi/essentia/build/src/examples/essentia_streaming_extractor_music_svm
    high_level_profile:
        highlevel:
            svm_models:
            - /home/dietpi/essentia/models/danceability.history
            - /home/dietpi/essentia/models/gender.history
            - /home/dietpi/essentia/models/genre_rosamerica.history
            - /home/dietpi/essentia/models/mood_acoustic.history
            - /home/dietpi/essentia/models/mood_aggressive.history
            - /home/dietpi/essentia/models/mood_electronic.history
            - /home/dietpi/essentia/models/mood_happy.history
            - /home/dietpi/essentia/models/mood_party.history
            - /home/dietpi/essentia/models/mood_relaxed.history
            - /home/dietpi/essentia/models/mood_sad.history
            - /home/dietpi/essentia/models/voice_instrumental.history
            compute: 1
        outputFormat: json
    low_level_targets:
        average_loudness:
            path: lowlevel.average_loudness
            type: float
            required: yes
        bpm:
            path: rhythm.bpm
            type: integer
            required: yes
        danceability:
            path: rhythm.danceability
            type: float
        beats_count:
            path: rhythm.beats_count
            type: integer
        initial_key:
            path: tonal.key_edma.key
            type: string
            required: yes
        key_strength:
            path: tonal.key_edma.strength
            type: float
            required: yes
        chords_key:
            path: tonal.chords_key
            type: string
            required: yes
        chords_scale:
            path: tonal.chords_scale
            type: string
            required: yes
        chords_changes_rate:
            path: tonal.chords_changes_rate
            type: float
            required: yes
        chords_number_rate:
            path: tonal.chords_number_rate
            type: float
            required: yes
    high_level_targets:
        danceable:
            path: highlevel.danceability.all.danceable
            type: float
            required: yes
        gender:
            path: highlevel.gender.value
            type: string
            required: yes
        is_male:
            path: highlevel.gender.all.male
            type: float
        is_female:
            path: highlevel.gender.all.female
            type: float
        genre_rosamerica:
            path: highlevel.genre_rosamerica.value
            type: string
            required: yes
        voice_instrumental:
            path: highlevel.voice_instrumental.value
            type: string
            required: yes
        is_voice:
            path: highlevel.voice_instrumental.all.voice
            type: float
            required: yes
        is_instrumental:
            path: highlevel.voice_instrumental.all.instrumental
            type: float
            required: yes
        mood_acoustic:
            path: highlevel.mood_acoustic.all.acoustic
            type: float
            required: yes
        mood_aggressive:
            path: highlevel.mood_aggressive.all.aggressive
            type: float
            required: yes
        mood_electronic:
            path: highlevel.mood_electronic.all.electronic
            type: float
            required: yes
        mood_happy:
            path: highlevel.mood_happy.all.happy
            type: float
            required: yes
        mood_party:
            path: highlevel.mood_party.all.party
            type: float
            required: yes
        mood_relaxed:
            path: highlevel.mood_relaxed.all.relaxed
            type: float
            required: yes
        mood_sad:
            path: highlevel.mood_sad.all.sad
            type: float
            required: yes
    low_level_profile:
        outputFormat: json
        outputFrames: 0
    chromaprint:
        compute: 0
